### PR TITLE
Fixed the bug for table not showing data in some cases when clicked on expand Button

### PR DESCRIPTION
**Pull request by ankitaparekh**
I have made the fix but I want to make sure that the performance is unchanged.It would be nice if someone can verify that before merging.

Thank you,
Ankita Parekh

### CODE REVIEW

**Comment by erfangc** [comment]
Thanks Ankita, instead of introducing all these props that must be passed
through all these layers of Compnents. Could you just recompute view
boundaries in the store reducer that handles he toggleCollapse.

If that store reducer does not have a reference to the viewPort or canvas
jquery object, then we could make them a state or a property of the store

(idk what the end product should look like, but I feel there is a less
cumbersome way. because giving Cell.tsx knowledge of the canvas and
viewport seems to break a lot of modularity and decoupling.)

**Comment by ankitaparekh** [comment]
Hey Erfang, Thank you for the comments.I have changed my approach and tried to implement it in the way you suggested,It would be great if you review it and test it  out on your dataset as well.

**Comment by erfangc** [comment]
Thanks Ankita, the changes are inline with what I was thinking about.

Why are some of the tests failing though?

**Comment by erfangc** [comment]
@ankitaparekh can you pull from `origin` to merge the unrelated updates I made. See if the tests are fixed.

also, the tests should not have been failing b/c what you changed should not have impacted Sorting. But i did see you committed some test data. That is probably why I imagine. Could you make sure when you commit, you revert the test data set to the original set?

**Comment by erfangc** [comment]
@ankitaparekh please clean up the merge and ensure tests pass - you included your own test JSON file instead of the original test dataset JSON

**Comment by erfangc** [comment]
There are merge conflicts

**Pull request closed without merging**
